import * as wmill from 'windmill-client';
import type { AuditLogEntry, CreatedPaymentLinkRecord, MerchantContext, PaymentStatus } from './types.ts';
import { redactSensitiveData } from './errors.ts';

// Registry persistente em variáveis Windmill.
// Resolve o caso em que um Pay by Link foi criado mas ainda não aparece na listagem da LusoPay.

const DEFAULT_WINDMILL_USER = 'tomaspaiva';
const MAX_LINK_RECORDS = 500;
const MAX_AUDIT_RECORDS = 1000;

function env(key: string): string | undefined {
  const deno = (globalThis as unknown as { Deno?: { env?: { get?: (key: string) => string | undefined } } }).Deno;
  return deno?.env?.get?.(key) || (globalThis as unknown as { process?: { env?: Record<string, string | undefined> } }).process?.env?.[key];
}

function safeMerchantId(merchantId: string) {
  return merchantId.replace(/[^a-zA-Z0-9_-]/g, '_');
}

function variablePrefix() {
  // Permite mudar o caminho das variáveis sem alterar código.
  const configured = env('LUSOPAY_STATE_VARIABLE_PREFIX');
  if (configured) return configured.replace(/\/$/, '');
  const user = env('WM_USERNAME') || env('WMILL_USERNAME') || DEFAULT_WINDMILL_USER;
  return `u/${user}`;
}

function registryPath(merchantId: string) {
  return `${variablePrefix()}/LUSOPAY_LINK_REGISTRY_${safeMerchantId(merchantId)}`;
}

function auditPath(merchantId: string) {
  return `${variablePrefix()}/LUSOPAY_AUDIT_LOG_${safeMerchantId(merchantId)}`;
}

async function readJsonArray<T>(path: string): Promise<T[]> {
  // Se a variável ainda não existir, tratamos como lista vazia.
  try {
    const raw = await wmill.getVariable(path);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed as T[] : [];
  } catch {
    return [];
  }
}

async function writeJsonArray<T>(path: string, records: T[], description: string) {
  await wmill.setVariable(path, JSON.stringify(records), false, description);
}

export async function listCreatedPaymentLinks(context: MerchantContext): Promise<CreatedPaymentLinkRecord[]> {
  return readJsonArray<CreatedPaymentLinkRecord>(registryPath(context.merchant_id));
}

export async function findCreatedPaymentLink(context: MerchantContext, orderId: string): Promise<CreatedPaymentLinkRecord | null> {
  const records = await listCreatedPaymentLinks(context);
  return records.find((record) => record.order_id === orderId) || null;
}

export async function saveCreatedPaymentLink(context: MerchantContext, record: CreatedPaymentLinkRecord) {
  // Upsert por order_id: evita duplicados quando o mesmo link é recriado/testado.
  const path = registryPath(context.merchant_id);
  const records = await readJsonArray<CreatedPaymentLinkRecord>(path);
  const next = [
    record,
    ...records.filter((item) => item.order_id !== record.order_id),
  ].slice(0, MAX_LINK_RECORDS);
  await writeJsonArray(path, next, 'LusoPay Pay by Link registry generated by the merchant MCP assistant');
}

export async function updateCreatedPaymentLinkState(
  context: MerchantContext,
  orderId: string,
  state: PaymentStatus,
  patch: Partial<CreatedPaymentLinkRecord> = {},
) {
  const path = registryPath(context.merchant_id);
  const records = await readJsonArray<CreatedPaymentLinkRecord>(path);
  const next = records.map((record) => (
    record.order_id === orderId
      ? { ...record, ...patch, state }
      : record
  ));
  await writeJsonArray(path, next, 'LusoPay Pay by Link registry generated by the merchant MCP assistant');
}

export async function appendAuditLog(context: MerchantContext, entry: Omit<AuditLogEntry, 'timestamp' | 'merchant_id'>) {
  // Auditoria curta e redigida para perceber o que aconteceu sem expor credenciais.
  const path = auditPath(context.merchant_id);
  const records = await readJsonArray<AuditLogEntry>(path);
  const next = [
    {
      timestamp: new Date().toISOString(),
      merchant_id: context.merchant_id,
      ...redactSensitiveData(entry),
    } as AuditLogEntry,
    ...records,
  ].slice(0, MAX_AUDIT_RECORDS);
  await writeJsonArray(path, next, 'LusoPay MCP audit log');
}
